### ISSUE TITLE
DirectX and Xinput both enabled by default

### ISSUE THREAD

**Issue by jeremybrown82** [garbear/xbmc#111]
Hi,

With a joystick such as the ds4 for ps4,  Direct input goes bonkers when configuring the joystick for an emulator. Xinput seems to work fine as a wrapper with the same hardware (ds4),though .

thought you would like to know

Jeremy

**Comment by garbear** [comment]
I shipped two joystick APIs so that one would work if the other failed. Is this what is happening to you?

**Comment by garbear** [comment]
Both APIs enabled by default is the desired behavior. I added a toggle so that if a driver misbehaves and sends input for two controllers then one API can be disabled.
