### ISSUE TITLE
Password Issue

### ISSUE THREAD

**Issue by I-Cat** [garbear/xbmc#124]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Hello 
I came acrossed transifex login credentials.
I logged in to TeamXBMC on transifex
I was going to add my self to the team but thats not fair.... lol
So I logged out and I can't make a pull request over at TeamXBMC / alanwww1 
To tell u to change the password and such.
plz unblock me from pull requests / issue reports.

@alanwww1
@garbear 

 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by garbear** [comment]
@I-Cat we take vulnerabilities like this very seriously. Thanks for bringing it to our attention!

We'd like to help you be even more effective in communicating these things and unblock your pull request / issue reports. We need to improve your communication for this to happen, because right now it's not acceptable. No offense, and I think you're just unaware that you're communicating improperly. I can offer help if you join the #kod-dev-freenode channel and get my attention.

**Comment by garbear** [comment]
The issue should be resolved, thanks for reporting.

**Comment by I-Cat** [comment]
> @I-Cat we take vulnerabilities like this very seriously. Thanks for bringing it to our attention!
>
> We'd like to help you be even more effective in communicating these things and unblock your pull request / issue reports. We need to improve your communication for this to happen, because right now it's not acceptable. No offense, and I think you're just unaware that you're communicating improperly. I can offer help if you join the #kod-dev-freenode channel and get my attention.

Yes I am sorry about the freenode. I am still trying to get the freenode channel to work. 😿 . 
The mIRC isnt working i will keep tring thou. 

Yep I feel better that it has been fix tnx.
