### ISSUE TITLE
Launching Fails if no savestates are present in latest nightly

### ISSUE THREAD

**Issue by zach-morris** [garbear/xbmc#132]
### Describe the bug
Here is a clear and concise description of what the problem is:

Launching will fail in the latest release RetroPlayer 20 (2023-02-01) if no savestates are present
https://forum.kodi.tv/showthread.php?tid=173361&pid=3139497#pid3139497

Adding an issue here for visibility.  Feel free to close this if you've already resolved

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Launching will not fail if no savestates are present

## Actual Behavior

If no savestates are present, the log shows:
```
No compatible game client selected
```
Even though there are compatible gameclients

## Possible Fix

It seems something was broken with the latest savestate implementation that missed accounting for no savestates?

### To Reproduce

1.   Start Kodi RetroPlayer 20 (2023-02-01)
2.   Validate a specific game addon is loaded
3.   Launch a compatible game with no savestate present

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [X] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: RetroPlayer 20 (2023-02-01)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by garbear** [comment]
Likely https://github.com/xbmc/xbmc/pull/22686. We had a dependency left over from the early days that made it hard to scale the out-of-game savestate dialog. Breaking this dependency must have broke the logic. I'm looking into it.

**Comment by garbear** [comment]
I've launched a round of test builds with https://github.com/xbmc/xbmc/pull/22751

**Comment by garbear** [comment]
Test builds uploaded: https://github.com/garbear/xbmc/releases

**Comment by zach-morris** [comment]
Works.  That was quick!

**Comment by garbear** [comment]
Aaaaaaaaand its already merged in master. I've already included it in the Nexus backport: https://github.com/xbmc/xbmc/pull/22750. Thanks for finding so quickly.
