### ISSUE TITLE
Retroplayer 21 Rock Pi 4 Plus Storage Partion problem in Image

### ISSUE THREAD

**Issue by Greydesk** [garbear/xbmc#138]
### Describe the bug
Here is a clear and concise description of what the problem is:

Images where problem occurs:
  LibreELEC-RK3399.arm-12.0-retroplayer-20231024-45dbbcd3-rock-pi-4-plus.img.gz
  LibreELEC-RK3399.arm-12.0-retroplayer-20231210-61dc79dc-rock-pi-4-plus.img.gz
After initial power on with resizing of partitions, receive the following error:
*** Error in mount_storage: mount_common: Could not mount UUID=5a7f8cd4-ed2b-4edd-b6a5-3bef0c8801c4 ***
### Starting debugging shell for boot step: mount_storage... type  exit  to quit ###

Image LibreELEC-RK3399.arm-11.0-retroplayer-20231205-178d04a4-rock-pi-4-plus.img.gz works properly.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expect the Rock Pi 4 plus to boot into Kodi

## Actual Behavior

Receive error:
*** Error in mount_storage: mount_common: Could not mount UUID=5a7f8cd4-ed2b-4edd-b6a5-3bef0c8801c4 ***
### To Reproduce

1.  Download LibreELEC-RK3399.arm-12.0-retroplayer-20231210-61dc79dc-rock-pi-4-plus.img.gz
2.  Extract Image
3.  Use USB Image Writer in Linux Mint Mate 21.2 Victoria to burn image to 64gb MicroSD card that works with other images.
4.  Place SD card in unit and power on.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Greydesk** [comment]
Also, when I put the MicroSD back in my laptop, Linux fails to automount the Storage partition and complains of a bad superblock.

**Comment by garbear** [comment]
Sorry, I missed this issue. A workaround was introduced in https://github.com/LibreELEC/LibreELEC.tv/pull/8532. I've included it in my 2024-01-29 round of builds: https://github.com/garbear/xbmc/releases
