### ISSUE TITLE
typo in xbmc/peripherals/addons/Makefile.in

### ISSUE THREAD

**Issue by frostworx** [garbear/xbmc#19]
can't build as of following typo:
-SRCS  = AddonJoytsickButtonMapper.cpp
+SRCS  = AddonJoystickButtonMapper.cpp

**Comment by garbear** [comment]
thanks! and good timing, i just cleaned up all my work over the last month. my `joysticks` branch is the one with my current joysticks progress

**Comment by garbear** [comment]
`joysticks` compiles with the typo fix. thanks again

similar to pvr-addons, if you run `git clone git://github.com/garbear/xbmc-peripheral-addons.git peripheral-addons` from the root repo directory, the joystick add-on will be built alongside kodi and automatically copied to addons/
