### ISSUE TITLE
README add link to build dependencies

### ISSUE THREAD

**Issue by davcri** [garbear/xbmc#25]
What about adding a link to [KODI build dependencies](http://kodi.wiki/view/HOW-TO:Compile_XBMC_for_Linux) in the README ? 

It would be useful to non experienced programmer like me. Yes, I tried to compile this fork of kodi, without downloading the dependencies :sweat:

---
However I'll write what I did to get a successful run of `./configure` 
on Arch Linux, maybe it would be useful for someone:
 
```
sudo pacman -Syu
sudo pacman -Sy swig boost nasm yasm gperf zip

./configure PYTHON_VERSION=2
# need to specify the Python version, otherwise this error will appear:
#    TypeError: unorderable types: str() >= int()
```

**Comment by a1rwulf** [comment]
It's not that easy.
Every distribution has it's own package philosophy.
ArchLinux' bleeding-edge approach of course has the latest python installed by default and you can have python 2.x beside.
And that's what you need to tell KODI.
I'm afraid that's the pain you have to go through, when wanting to compile and develop KODI.

**Comment by davcri** [comment]
Sure, I didn't want to force anyone to write distribution specific guides. 

I was only asking to add a link to the existing wiki page: http://kodi.wiki/view/HOW-TO:Compile_XBMC_for_Linux

**Comment by a1rwulf** [comment]
ok now I got you.
Thought that anyone having kodi cloned has already read the wiki guide on how to compile it ;)

**Comment by garbear** [comment]
hi davcri,

sorry for pain in building Kodi and that I can't be of more help with arch depends, build systems really aren't my thing

i really want the build system to be as frictionless as possible for ppl trying to contribute. while I can't help with Kodi, i've put a lot of work into documenting the process for building binary add-ons like [game.libretro](https://github.com/kodi-game/game.libretro). it relies on our new cmake build system that i've literally spent weeks trying to master. if you get past the arch depends problem, then I hope at least the instructions in that readme will make building binary add-ons less painful than building Kodi

as always, if you are victorious in your battle to build Kodi, i'm sure the "next guy" would appreciate it if you documented your struggles like i did with binary add-ons. thanks!

**Comment by davcri** [comment]
Just created a pull request, maybe it's easy to explain what I'm proposing here :smile: 

However thank you for your great work ! I'm really looking forward to see Retroplayer in future Kodi releases ! 

>
i've put a lot of work into documenting the process for building binary add-ons like game.libretro. it relies on our new cmake build system that i've literally spent weeks trying to master. if you get past the arch depends problem, then I hope at least the instructions in that readme will make building binary add-ons less painful than building Kodi

Yes the add-ons seem to compile quite smoothly, however yesterday I gave up because of a problem with _make install_. 

>
as always, if you are victorious in your battle to build Kodi, i'm sure the "next guy" would appreciate it if you documented your struggles like i did with binary add-ons. thanks!
Sure ! Actually I only succed with run _./configure_ without problem (it's all written in the first post).

**Comment by davcri** [comment]
Issue closed.
If I'll find a way to compile & try on Arch, I'll report !

**Comment by garbear** [comment]
LOL sorry if you got an email each time I force-pushed. the readme change has been squashed into the new default branch, retroplayer-15alpha2 (see http://forum.kodi.tv/showthread.php?tid=223146) so if you were getting a million emails you won't anymore :)

**Comment by garbear** [comment]
also I updated the build instructions for add-ons, see the new Readme at https://github.com/garbear/xbmc

**Comment by davcri** [comment]
>
LOL sorry if you got an email each time I force-pushed. the readme change has been squashed into the new default branch, retroplayer-15alpha2 (see http://forum.kodi.tv/showthread.php?tid=223146) so if you were getting a million emails you won't anymore :)

I didn't receive any mail, and I'm subscribed to this issue :smile: 

Great work, I wish I could have the knowledge to help you with this.
