### ISSUE TITLE
build all add-ons of a single type

### ISSUE THREAD

**Issue by garbear** [garbear/xbmc#38]
@wsnipex, @montellese, @notspiff: Is there any way to build all game add-ons in one command? right now my build command looks like `rm .installed-macosx10.10_x86_64-target ; make ADDONS="peripheral.joystick game.libretro game.libretro.2048 game.libretro.beetle-bsnes game.libretro.beetle-pce-fast game.libretro.bnes game.libretro.dosbox game.libretro.fceumm game.libretro.genplus game.libretro.mupen64plus game.libretro.nestopia game.libretro.quicknes game.libretro.yabause"`

**Comment by Montellese** [comment]
It's currently not possible but I thought about this as well in the past.

**Comment by wsnipex** [comment]
yes, I've missed that as well for a long time. Will implement it.

**Comment by wsnipex** [comment]
can you try https://github.com/wsnipex/xbmc/commit/46af27ea8b30ad373213ddbfefb833f32c578120
This allows you to 
>cmake -DADDONS_TO_BUILD=game[.*]

**Comment by garbear** [comment]
works like a charm. thanks
