### ISSUE TITLE
Build with CMake

### ISSUE THREAD

**Issue by fetzerch** [garbear/xbmc#54]
Hi @garbear,

I hope it's ok to misuse an issue for the topic, but I'd have a question on your binary addons extension.

When you build Kodi with CMake you can now develop binary addons against it by just building an addon with `cmake -DKODI_BUILD_DIR=<kodi build dir> -DCMAKE_PREFIX_PATH=<kodi build dir>/build <myaddon source dir>`. This also deploys the addon in the kodi build dir, so that Kodi finds it. If I apply https://github.com/xbmc/xbmc/pull/9804 and https://github.com/xbmc/xbmc/pull/9671, this also works with your retroplayer branch. I've tested `game.libretro` and `peripheral.joystick`.

Do you or maybe @notspiff have an idea how we could do the same thing for the cores? Their CMake file just do a `find_package(<LIBRETRO CORE>)` which fails because the core has not been built.

What I'm looking for is basically a simple way to build and deploy a core in debug mode to launch it for debugging with a self compiled kodi.

Thanks much,
Christian

**Comment by garbear** [comment]
The libretro cores are specified as dependencies. Does building against Kodi also process the dependencies?

**Comment by notspiff** [comment]
originally we built the core with the main program. the build on windows relies on a supplied mingw environment. this environment is a dependency on windows. in the process of adding this, the cores were made dependencies themself for some reason. i guess it was the familiarity of specifying url et al in a .txt file that was attractive.

**Comment by notspiff** [comment]
shameless self-plug on top of your self-plug; https://github.com/notspiff/xbmc/commits/stuff_for_sheeps contains some stuff related to this. if you want to test it you can use e.g. https://github.com/notspiff/screensaver.electricsheep to see it in action. if you in the process happen to confirm that my shit works on a second machine that would be just a tragedy.

**Comment by garbear** [comment]
Can this be closed?
