### ISSUE TITLE
kodiConfig.cmake is now KodiConfig.cmake

### ISSUE THREAD

**Issue by craigcarnell** [garbear/xbmc#64]
causes the build to fail for the addons

**Comment by garbear** [comment]
Thanks for the report. What needs to be updated? @hudokkow made the herculean effort of updating all add-ons to use a capitalized CMake module (see https://github.com/kodi-game/game.libretro.4do/commit/fa87305). Do other changes need to be made?

**Comment by hudokkow** [comment]
Need to know which addons, Kodi branch/version used, etc? Can you upload a build log somewhere?

In the middle of quite a few addons I might have missed something.

**Comment by garbear** [comment]
@craigcarnell have you tried recently? is this still a problem?
