### ISSUE TITLE
[Feature Request]  vfs.libarchive

### ISSUE THREAD

**Issue by zach-morris** [garbear/xbmc#96]
vfs.libarchive is not yet included (for OSX).  Coincidentally it's not in the nightly builds either.  I've tried to build it myself but can't get it to compile (although I'm fairly certain thats just my lack of knowledge with compiling on a mac).

**Comment by garbear** [comment]
Hm, it should be included: https://github.com/xbmc/repo-binary-addons/commit/4748fe5

**Comment by zach-morris** [comment]
Yeah, I saw that it should be in there, but it's not.  I just downloaded the latest OSX nightly (e6591830) and opened the package to be sure.  It's not included, nor is it included in your last build that I could find.

**Comment by garbear** [comment]
Compilation must be broken. The fix is probably trivial. I'll get a log and see if I can fix it, but maybe not this weekend.

**Comment by garbear** [comment]
vfs.libarchive compiles for me using the instructions in the readme. I've launched some Jenkins builds to see if they are having problems compiling.

**Comment by garbear** [comment]
Compile log from latest jenkins build:

```
CMake Error at FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  FindOpenSSL.cmake:388 (find_package_handle_standard_args)
  CMakeLists.txt:16 (find_package)

-- Configuring incomplete, errors occurred!
```

@notspiff do you know of an add-on that builds OpenSSL successfully?

**Comment by zach-morris** [comment]
Closing as this is not specific to retroplayer branch
